### ISSUE TITLE
Not Loading 

### ISSUE THREAD

**Issue by Kawaza** [JosephAnson/mrt-notes#185]
### Describe the bug

Cant change the instance or the boss without it loading indefinitely and eventually just not working.

Page: https://mrt-notes.vercel.app/playground

### Reproduction

All the drop downs

### System Info

```Shell
Nothing
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/josephanson/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/josephanson/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nukel** [comment]
i have too this problem...

**Comment by JosephAnson** [comment]
Are you still receiving this issue? Sorry to be late in responding.

**Comment by Kawaza** [comment]
@JosephAnson This seems to be fixed now thank you. I will add a few more things I did notice when playing around with it.

- On the homepage the "Create Note" button doesnt do anything
- Also on the homepage if you click on a boss or dungeon , it brings you down but doesnt filter it but if you click it again then it filters it.

**Comment by JosephAnson** [comment]
Those two fixes should also be fixed, deploying them to production now.

Thanks for reporting them ❤️
